// js/script.js - Traductor Offline Completo

// Mostrar secciones (usa en el HTML con onclick="mostrarSeccion('id')")
function mostrarSeccion(id) {
  document.querySelectorAll(".section").forEach(sec => sec.classList.remove("active"));
  const el = document.getElementById(id);
  if (el) el.classList.add("active");
}

// ==================== DICCIONARIO DE TRADUCCIONES ====================
const translations = {
  es: {
    titleName: "Sherval",
    titleSub: "Innovación en Desarrollo de Software",
    navVision: "Visión",
    navMision: "Misión",
    navValores: "Valores",
    navHistoria: "Historia",
    navColores: "Colores",
    navServicios: "Servicios",
    navPropuesta: "Propuesta",
    navCanales: "Canales de pago",
    navContacto: "Contáctanos",
    navAudio: "Audio",
    visionTitle: "✨ Visión",
    visionText: "Llegar a ser <strong>líderes en el desarrollo de software innovador</strong> en Colombia y la región, siendo reconocidos por nuestra capacidad de anticiparnos a las necesidades del mercado y ofrecer soluciones tecnológicas que transforman industrias.",
    visionText2: "Aspiramos a convertirnos en el socio tecnológico preferido de empresas que buscan innovación, calidad y compromiso, expandiendo nuestro alcance a nivel internacional y contribuyendo al desarrollo tecnológico de la región.",
    misionTitle: "🚀 Misión",
    misionText: "Desarrollar <strong>soluciones de software innovadoras y de alta calidad</strong> que impulsen el crecimiento y la eficiencia de nuestros clientes, a través de la excelencia técnica, la colaboración estrecha y un compromiso inquebrantable con la satisfacción de nuestros usuarios.",
    misionText2: "Nos esforzamos por comprender las necesidades únicas de cada cliente y transformarlas en productos tecnológicos robustos, escalables y fáciles de usar que generen valor real para sus negocios.",
    valoresTitle: "💎 Valores Corporativos",
    valoresIntro: "Nuestros valores son los pilares que guían cada decisión, proyecto y relación con nuestros clientes:",
    valor1Title: "1. Respeto",
    valor1Desc: "Tendremos en cuenta lo que quiera el cliente y lo orientaremos de la mejor manera posible. Valoramos las ideas y necesidades de cada persona.",
    valor2Title: "2. Responsabilidad",
    valor2Desc: "Entregaremos lo prometido a tiempo y nos comprometeremos profundamente con el éxito de cada proyecto. Nuestros clientes pueden confiar en nosotros.",
    valor3Title: "3. Honestidad",
    valor3Desc: "Los trabajos llevarán un proceso transparente y sin tabúes con el cliente. Comunicamos abiertamente sobre avances, desafíos y soluciones.",
    valor4Title: "4. Eficiencia",
    valor4Desc: "Los recursos del sistema serán fáciles de utilizar y modificar, además de contar con garantía. Optimizamos procesos y recursos para entregar el máximo valor.",
    valor5Title: "5. Durabilidad",
    valor5Desc: "Los programas y trabajos serán bastante resistentes con el paso del tiempo. Desarrollamos software pensando en el largo plazo.",
    valor6Title: "6. Seguridad",
    valor6Desc: "Esta se ofrecerá de manera permanente durante todo el proceso con los usuarios. La protección de datos es una prioridad en cada línea de código.",
    valor7Title: "7. Perseverancia",
    valor7Desc: "Mantendremos constancia hasta escalar los objetivos de la empresa. No nos rendimos ante los desafíos y buscamos continuamente mejorar.",
    historiaTitle: "📖 Historia",
    historiaText: "<strong>Sherval</strong> es una empresa creada por dos jóvenes apasionados por la programación: <strong>Sherman Andrés León Trigos</strong> y <strong>Laura Valentina Hernández Gómez</strong>, formados en <strong>Programación de Software en el SENA</strong>.",
    historiaText2: "Nuestra empresa nació de un proyecto final académico que se transformó en una empresa consolidada con visión de futuro. Compartimos una misión común: crear soluciones tecnológicas innovadoras que marquen la diferencia en la vida de las personas y el crecimiento de las empresas.",
    coloresTitle: "🎨 Colores Corporativos",
    coloresText: "Los colores utilizados en nuestra marca transmiten significados importantes que reflejan nuestra identidad y valores:",
    color1Name: "🔷 Azul Oscuro",
    color1Label: "Significado:",
    color1Meaning: "Serenidad, confianza, inteligencia y profesionalismo",
    color1AppLabel: "Aplicación:",
    color1App: "Color principal en logo y materiales corporativos",
    color2Name: "⚪ Plateado",
    color2Label: "Significado:",
    color2Meaning: "Pureza, innovación, modernidad y humildad",
    color2AppLabel: "Aplicación:",
    color2App: "Acentos y detalles visuales tecnológicos",
    color3Name: "⬛ Negro",
    color3Label: "Significado:",
    color3Meaning: "Elegancia innata, solidez y sofisticación",
    color3AppLabel: "Aplicación:",
    color3App: "Tipografía y elementos estructurales",
    color4Name: "🟧 Dorado/Naranja",
    color4Label: "Significado:",
    color4Meaning: "Creatividad, energía, innovación y dinamismo",
    color4AppLabel: "Aplicación:",
    color4App: "Elementos de énfasis y llamadas a la acción",
    serviciosTitle: "💻 Servicios Ofrecidos",
    serviciosText: "En Sherval ofrecemos una amplia gama de servicios de desarrollo de software diseñados para satisfacer las necesidades específicas de cada cliente:",
    service1Title: "🖥️ Desarrollo de Software a Medida",
    service1Desc: "Creamos soluciones personalizadas que se adaptan perfectamente a los requisitos únicos de su negocio.",
    service2Title: "📱 Aplicaciones Móviles",
    service2Desc: "Diseñamos y desarrollamos apps nativas y multiplataforma para iOS y Android con interfaces intuitivas.",
    service3Title: "🌐 Desarrollo de Páginas Web",
    service3Desc: "Creamos sitios web responsivos y optimizados, desde landing pages hasta plataformas complejas.",
    service4Title: "📚 Asesorías y Capacitación",
    service4Desc: "Brindamos asesorías para personas y empresas que quieran profesionalizarse en el área tecnológica.",
    service5Title: "🔗 Integración de Sistemas",
    service5Desc: "Conectamos diferentes aplicaciones y sistemas para mejorar la eficiencia operativa de su empresa.",
    service6Title: "🧪 Pruebas de Software (QA)",
    service6Desc: "Realizamos pruebas exhaustivas de calidad para garantizar el funcionamiento perfecto de su software.",
    service7Title: "🔧 Mantenimiento y Soporte",
    service7Desc: "Ofrecemos servicios continuos de mantenimiento, actualizaciones y soporte técnico especializado.",
    service8Title: "☁️ Soluciones en la Nube",
    service8Desc: "Implementamos y gestionamos soluciones cloud para mayor escalabilidad y seguridad.",
    propuestaTitle: "💡 Propuesta",
    propuestaText: "Somos una empresa dedicada a crear soluciones tecnológicas innovadoras que impulsen el crecimiento y la eficiencia de nuestros clientes.",
    canalesTitle: "💰 Canales de pago",
    canalesText: "Recibimos pagos a través de Nequi, Daviplata y PayPal.",
    contactoTitle: "📞 Contáctanos",
    contactEmail1: "📧 Correo:",
    contactPhone1: "📱 Teléfono:",
    contactRole1: "💼 Cargo:",
    contactRoleText1: "Co-fundador & Desarrollador",
    contactEmail2: "📧 Correo:",
    contactPhone2: "📱 Teléfono:",
    contactRole2: "💼 Cargo:",
    contactRoleText2: "Co-fundadora & Desarrolladora",
    contactAddress: "📍 Dirección:",
    contactFormation: "🏢 Formación:",
    contactFormationText: "SENA - Técnicos en Programación de Software",
    contactSchedule: "⏰ Horario de atención:",
    contactScheduleText: "Lunes a Viernes 8:00 AM - 6:00 PM",
    audioTitle: "🔊 Audio Explicativo",
    audioText: "Escucha la explicación del proyecto:",
    footer1: "© Laura Valentina Hernández Gómez",
    footer2: "© Sherman Andrés León Trigos",
    footer3: "<strong>Programadores Profesionales de Software</strong>"
  },

  en: {
    titleName: "Sherval",
    titleSub: "Innovation in Software Development",
    navVision: "Vision",
    navMision: "Mission",
    navValores: "Values",
    navHistoria: "History",
    navColores: "Colors",
    navServicios: "Services",
    navPropuesta: "Proposal",
    navCanales: "Payment Methods",
    navContacto: "Contact Us",
    navAudio: "Audio",
    visionTitle: "✨ Vision",
    visionText: "To become <strong>leaders in innovative software development</strong> in Colombia and the region, recognized for our ability to anticipate market needs and offer technological solutions that transform industries.",
    visionText2: "We aspire to become the preferred technology partner for companies seeking innovation, quality and commitment, expanding our reach internationally and contributing to the technological development of the region.",
    misionTitle: "🚀 Mission",
    misionText: "Develop <strong>innovative, high-quality software solutions</strong> that drive growth and efficiency for our clients through technical excellence, close collaboration and an unwavering commitment to user satisfaction.",
    misionText2: "We strive to understand each client's unique needs and transform them into robust, scalable and easy-to-use technology products that generate real value for their businesses.",
    valoresTitle: "💎 Corporate Values",
    valoresIntro: "Our values are the pillars that guide every decision, project and relationship with our clients:",
    valor1Title: "1. Respect",
    valor1Desc: "We take into account what the client wants and guide them in the best possible way. We value the ideas and needs of each person.",
    valor2Title: "2. Responsibility",
    valor2Desc: "We deliver what is promised on time and are deeply committed to the success of each project. Our clients can trust us.",
    valor3Title: "3. Honesty",
    valor3Desc: "Work will follow a transparent process with no taboos with the client. We communicate openly about progress, challenges and solutions.",
    valor4Title: "4. Efficiency",
    valor4Desc: "System resources will be easy to use and modify, and will come with a warranty. We optimize processes and resources to deliver maximum value.",
    valor5Title: "5. Durability",
    valor5Desc: "Programs and work will be quite resistant over time. We develop software with the long term in mind.",
    valor6Title: "6. Security",
    valor6Desc: "This will be offered permanently throughout the entire process with users. Data protection is a priority in every line of code.",
    valor7Title: "7. Perseverance",
    valor7Desc: "We will maintain consistency to scale the company's objectives. We don't give up in the face of challenges and continuously seek to improve.",
    historiaTitle: "📖 History",
    historiaText: "<strong>Sherval</strong> is a company created by two young people passionate about programming: <strong>Sherman Andrés León Trigos</strong> and <strong>Laura Valentina Hernández Gómez</strong>, trained in <strong>Software Programming at SENA</strong>.",
    historiaText2: "Our company was born from a final academic project that transformed into a consolidated company with a vision for the future. We share a common mission: to create innovative technological solutions that make a difference in people's lives and business growth.",
    coloresTitle: "🎨 Corporate Colors",
    coloresText: "The colors used in our brand convey important meanings that reflect our identity and values:",
    color1Name: "🔷 Dark Blue",
    color1Label: "Meaning:",
    color1Meaning: "Serenity, trust, intelligence and professionalism",
    color1AppLabel: "Application:",
    color1App: "Main color in logo and corporate materials",
    color2Name: "⚪ Silver",
    color2Label: "Meaning:",
    color2Meaning: "Purity, innovation, modernity and humility",
    color2AppLabel: "Application:",
    color2App: "Accents and technological visual details",
    color3Name: "⬛ Black",
    color3Label: "Meaning:",
    color3Meaning: "Innate elegance, solidity and sophistication",
    color3AppLabel: "Application:",
    color3App: "Typography and structural elements",
    color4Name: "🟧 Gold/Orange",
    color4Label: "Meaning:",
    color4Meaning: "Creativity, energy, innovation and dynamism",
    color4AppLabel: "Application:",
    color4App: "Emphasis elements and calls to action",
    serviciosTitle: "💻 Services Offered",
    serviciosText: "At Sherval we offer a wide range of software development services designed to meet the specific needs of each client:",
    service1Title: "🖥️ Custom Software Development",
    service1Desc: "We create customized solutions that perfectly fit your business's unique requirements.",
    service2Title: "📱 Mobile Applications",
    service2Desc: "We design and develop native and cross-platform apps for iOS and Android with intuitive interfaces.",
    service3Title: "🌐 Web Development",
    service3Desc: "We create responsive and optimized websites, from landing pages to complex platforms.",
    service4Title: "📚 Consulting and Training",
    service4Desc: "We provide consulting for people and companies who want to become professional in the technology area.",
    service5Title: "🔗 Systems Integration",
    service5Desc: "We connect different applications and systems to improve your company's operational efficiency.",
    service6Title: "🧪 Software Testing (QA)",
    service6Desc: "We perform exhaustive quality testing to ensure your software works perfectly.",
    service7Title: "🔧 Maintenance and Support",
    service7Desc: "We offer continuous maintenance, updates and specialized technical support services.",
    service8Title: "☁️ Cloud Solutions",
    service8Desc: "We implement and manage cloud solutions for greater scalability and security.",
    propuestaTitle: "💡 Proposal",
    propuestaText: "We are a company dedicated to creating innovative technological solutions that drive the growth and efficiency of our clients.",
    canalesTitle: "💰 Payment Methods",
    canalesText: "We accept Nequi, Daviplata and PayPal.",
    contactoTitle: "📞 Contact Us",
    contactEmail1: "📧 Email:",
    contactPhone1: "📱 Phone:",
    contactRole1: "💼 Position:",
    contactRoleText1: "Co-founder & Developer",
    contactEmail2: "📧 Email:",
    contactPhone2: "📱 Phone:",
    contactRole2: "💼 Position:",
    contactRoleText2: "Co-founder & Developer",
    contactAddress: "📍 Address:",
    contactFormation: "🏢 Education:",
    contactFormationText: "SENA - Software Programming Technicians",
    contactSchedule: "⏰ Office Hours:",
    contactScheduleText: "Monday to Friday 8:00 AM - 6:00 PM",
    audioTitle: "🔊 Audio Explanation",
    audioText: "Listen to the project explanation:",
    footer1: "© Laura Valentina Hernández Gómez",
    footer2: "© Sherman Andrés León Trigos",
    footer3: "<strong>Professional Software Developers</strong>"
  },

  fr: {
    titleName: "Sherval",
    titleSub: "Innovation dans le Développement de Logiciels",
    navVision: "Vision",
    navMision: "Mission",
    navValores: "Valeurs",
    navHistoria: "Histoire",
    navColores: "Couleurs",
    navServicios: "Services",
    navPropuesta: "Proposition",
    navCanales: "Moyens de paiement",
    navContacto: "Contactez-nous",
    navAudio: "Audio",
    visionTitle: "✨ Vision",
    visionText: "Devenir des <strong>leaders dans le développement de logiciels innovants</strong> en Colombie et dans la région, reconnus pour notre capacité à anticiper les besoins du marché et à offrir des solutions technologiques qui transforment les industries.",
    visionText2: "Nous aspirons à devenir le partenaire technologique préféré des entreprises qui recherchent l'innovation, la qualité et l'engagement, en élargissant notre portée à l'échelle internationale et en contribuant au développement technologique de la région.",
    misionTitle: "🚀 Mission",
    misionText: "Développer des <strong>solutions logicielles innovantes et de haute qualité</strong> qui favorisent la croissance et l'efficacité de nos clients, grâce à l'excellence technique, la collaboration étroite et un engagement inébranlable envers la satisfaction des utilisateurs.",
    misionText2: "Nous nous efforçons de comprendre les besoins uniques de chaque client et de les transformer en produits technologiques robustes, évolutifs et faciles à utiliser qui génèrent une valeur réelle pour leurs entreprises.",
    valoresTitle: "💎 Valeurs Corporatives",
    valoresIntro: "Nos valeurs sont les piliers qui guident chaque décision, projet et relation avec nos clients:",
    valor1Title: "1. Respect",
    valor1Desc: "Nous prenons en compte ce que le client souhaite et le guidons de la meilleure façon possible. Nous valorisons les idées et les besoins de chaque personne.",
    valor2Title: "2. Responsabilité",
    valor2Desc: "Nous livrons ce qui est promis à temps et nous nous engageons profondément dans le succès de chaque projet. Nos clients peuvent nous faire confiance.",
    valor3Title: "3. Honnêteté",
    valor3Desc: "Le travail suivra un processus transparent sans tabous avec le client. Nous communiquons ouvertement sur les progrès, les défis et les solutions.",
    valor4Title: "4. Efficacité",
    valor4Desc: "Les ressources du système seront faciles à utiliser et à modifier, et seront garanties. Nous optimisons les processus et les ressources pour offrir une valeur maximale.",
    valor5Title: "5. Durabilité",
    valor5Desc: "Les programmes et le travail seront assez résistants dans le temps. Nous développons des logiciels en pensant au long terme.",
    valor6Title: "6. Sécurité",
    valor6Desc: "Cela sera offert en permanence tout au long du processus avec les utilisateurs. La protection des données est une priorité dans chaque ligne de code.",
    valor7Title: "7. Persévérance",
    valor7Desc: "Nous maintiendrons la cohérence pour atteindre les objectifs de l'entreprise. Nous n'abandonnons pas face aux défis et cherchons continuellement à nous améliorer.",
    historiaTitle: "📖 Histoire",
    historiaText: "<strong>Sherval</strong> est une entreprise créée par deux jeunes passionnés de programmation: <strong>Sherman Andrés León Trigos</strong> et <strong>Laura Valentina Hernández Gómez</strong>, formés en <strong>Programmation de Logiciels au SENA</strong>.",
    historiaText2: "Notre entreprise est née d'un projet académique final qui s'est transformé en une entreprise consolidée avec une vision d'avenir. Nous partageons une mission commune: créer des solutions technologiques innovantes qui font la différence dans la vie des gens et la croissance des entreprises.",
    coloresTitle: "🎨 Couleurs Corporatives",
    coloresText: "Les couleurs utilisées dans notre marque transmettent des significations importantes qui reflètent notre identité et nos valeurs:",
    color1Name: "🔷 Bleu Foncé",
    color1Label: "Signification:",
    color1Meaning: "Sérénité, confiance, intelligence et professionnalisme",
    color1AppLabel: "Application:",
    color1App: "Couleur principale dans le logo et les matériaux corporatifs",
    color2Name: "⚪ Argenté",
    color2Label: "Signification:",
    color2Meaning: "Pureté, innovation, modernité et humilité",
    color2AppLabel: "Application:",
    color2App: "Accents et détails visuels technologiques",
    color3Name: "⬛ Noir",
    color3Label: "Signification:",
    color3Meaning: "Élégance innée, solidité et sophistication",
    color3AppLabel: "Application:",
    color3App: "Typographie et éléments structurels",
    color4Name: "🟧 Or/Orange",
    color4Label: "Signification:",
    color4Meaning: "Créativité, énergie, innovation et dynamisme",
    color4AppLabel: "Application:",
    color4App: "Éléments d'emphase et appels à l'action",
    serviciosTitle: "💻 Services Offerts",
    serviciosText: "Chez Sherval, nous offrons une large gamme de services de développement logiciel conçus pour répondre aux besoins spécifiques de chaque client:",
    service1Title: "🖥️ Développement de Logiciels sur Mesure",
    service1Desc: "Nous créons des solutions personnalisées qui s'adaptent parfaitement aux exigences uniques de votre entreprise.",
    service2Title: "📱 Applications Mobiles",
    service2Desc: "Nous concevons et développons des applications natives et multiplateformes pour iOS et Android avec des interfaces intuitives.",
    service3Title: "🌐 Développement Web",
    service3Desc: "Nous créons des sites web réactifs et optimisés, des pages d'atterrissage aux plateformes complexes.",
    service4Title: "📚 Conseil et Formation",
    service4Desc: "Nous fournissons des conseils aux personnes et aux entreprises qui souhaitent se professionnaliser dans le domaine technologique.",
    service5Title: "🔗 Intégration de Systèmes",
    service5Desc: "Nous connectons différentes applications et systèmes pour améliorer l'efficacité opérationnelle de votre entreprise.",
    service6Title: "🧪 Tests Logiciels (QA)",
    service6Desc: "Nous effectuons des tests de qualité exhaustifs pour garantir que votre logiciel fonctionne parfaitement.",
    service7Title: "🔧 Maintenance et Support",
    service7Desc: "Nous offrons des services continus de maintenance, de mises à jour et de support technique spécialisé.",
    service8Title: "☁️ Solutions Cloud",
    service8Desc: "Nous mettons en œuvre et gérons des solutions cloud pour une plus grande évolutivité et sécurité.",
    propuestaTitle: "💡 Proposition",
    propuestaText: "Nous sommes une entreprise dédiée à la création de solutions technologiques innovantes qui favorisent la croissance et l'efficacité de nos clients.",
    canalesTitle: "💰 Moyens de Paiement",
    canalesText: "Nous acceptons Nequi, Daviplata et PayPal.",
    contactoTitle: "📞 Contactez-nous",
    contactEmail1: "📧 Email:",
    contactPhone1: "📱 Téléphone:",
    contactRole1: "💼 Poste:",
    contactRoleText1: "Co-fondateur & Développeur",
    contactEmail2: "📧 Email:",
    contactPhone2: "📱 Téléphone:",
    contactRole2: "💼 Poste:",
    contactRoleText2: "Co-fondatrice & Développeuse",
    contactAddress: "📍 Adresse:",
    contactFormation: "🏢 Formation:",
    contactFormationText: "SENA - Techniciens en Programmation de Logiciels",
    contactSchedule: "⏰ Heures de bureau:",
    contactScheduleText: "Lundi à Vendredi 8h00 - 18h00",
    audioTitle: "🔊 Explication Audio",
    audioText: "Écoutez l'explication du projet:",
    footer1: "© Laura Valentina Hernández Gómez",
    footer2: "© Sherman Andrés León Trigos",
    footer3: "<strong>Développeurs de Logiciels Professionnels</strong>"
  },

  de: {
    titleName: "Sherval",
    titleSub: "Innovation in der Softwareentwicklung",
    navVision: "Vision",
    navMision: "Mission",
    navValores: "Werte",
    navHistoria: "Geschichte",
    navColores: "Farben",
    navServicios: "Dienstleistungen",
    navPropuesta: "Vorschlag",
    navCanales: "Zahlungsmethoden",
    navContacto: "Kontaktieren Sie uns",
    navAudio: "Audio",
    visionTitle: "✨ Vision",
    visionText: "<strong>Führend in der innovativen Softwareentwicklung</strong> in Kolumbien und der Region zu werden, anerkannt für unsere Fähigkeit, Marktbedürfnisse vorauszusehen und technologische Lösungen anzubieten, die Branchen transformieren.",
    visionText2: "Wir streben danach, der bevorzugte Technologiepartner für Unternehmen zu werden, die Innovation, Qualität und Engagement suchen, unsere Reichweite international zu erweitern und zur technologischen Entwicklung der Region beizutragen.",
    misionTitle: "🚀 Mission",
    misionText: "<strong>Innovative, hochwertige Softwarelösungen</strong> entwickeln, die das Wachstum und die Effizienz unserer Kunden durch technische Exzellenz, enge Zusammenarbeit und ein unerschütterliches Engagement für die Benutzerzufriedenheit fördern.",
    misionText2: "Wir bemühen uns, die einzigartigen Bedürfnisse jedes Kunden zu verstehen und sie in robuste, skalierbare und benutzerfreundliche Technologieprodukte zu verwandeln, die echten Wert für ihre Unternehmen generieren.",
    valoresTitle: "💎 Unternehmenswerte",
    valoresIntro: "Unsere Werte sind die Säulen, die jede Entscheidung, jedes Projekt und jede Beziehung zu unseren Kunden leiten:",
    valor1Title: "1. Respekt",
    valor1Desc: "Wir berücksichtigen, was der Kunde wünscht, und leiten ihn auf die bestmögliche Weise. Wir schätzen die Ideen und Bedürfnisse jeder Person.",
    valor2Title: "2. Verantwortung",
    valor2Desc: "Wir liefern das Versprochene pünktlich und engagieren uns zutiefst für den Erfolg jedes Projekts. Unsere Kunden können uns vertrauen.",
    valor3Title: "3. Ehrlichkeit",
    valor3Desc: "Die Arbeit folgt einem transparenten Prozess ohne Tabus mit dem Kunden. Wir kommunizieren offen über Fortschritte, Herausforderungen und Lösungen.",
    valor4Title: "4. Effizienz",
    valor4Desc: "Systemressourcen sind einfach zu verwenden und zu modifizieren und werden garantiert. Wir optimieren Prozesse und Ressourcen, um maximalen Wert zu liefern.",
    valor5Title: "5. Haltbarkeit",
    valor5Desc: "Programme und Arbeit sind im Laufe der Zeit ziemlich widerstandsfähig. Wir entwickeln Software mit Blick auf die lange Frist.",
    valor6Title: "6. Sicherheit",
    valor6Desc: "Dies wird während des gesamten Prozesses mit den Benutzern dauerhaft angeboten. Datenschutz hat in jeder Codezeile Priorität.",
    valor7Title: "7. Ausdauer",
    valor7Desc: "Wir werden Beständigkeit beibehalten, um die Ziele des Unternehmens zu skalieren. Wir geben nicht auf angesichts von Herausforderungen und streben kontinuierlich nach Verbesserung.",
    historiaTitle: "📖 Geschichte",
    historiaText: "<strong>Sherval</strong> ist ein Unternehmen, das von zwei jungen Menschen gegründet wurde, die sich für Programmierung begeistern: <strong>Sherman Andrés León Trigos</strong> und <strong>Laura Valentina Hernández Gómez</strong>, ausgebildet in <strong>Softwareprogrammierung am SENA</strong>.",
    historiaText2: "Unser Unternehmen entstand aus einem abschließenden akademischen Projekt, das sich in ein konsolidiertes Unternehmen mit Zukunftsvision verwandelte. Wir teilen eine gemeinsame Mission: innovative technologische Lösungen zu schaffen, die einen Unterschied im Leben der Menschen und im Unternehmenswachstum machen.",
    coloresTitle: "🎨 Unternehmensfarben",
    coloresText: "Die in unserer Marke verwendeten Farben vermitteln wichtige Bedeutungen, die unsere Identität und Werte widerspiegeln:",
    color1Name: "🔷 Dunkelblau",
    color1Label: "Bedeutung:",
    color1Meaning: "Gelassenheit, Vertrauen, Intelligenz und Professionalität",
    color1AppLabel: "Anwendung:",
    color1App: "Hauptfarbe im Logo und Unternehmensmaterialien",
    color2Name: "⚪ Silber",
    color2Label: "Bedeutung:",
    color2Meaning: "Reinheit, Innovation, Modernität und Bescheidenheit",
    color2AppLabel: "Anwendung:",
    color2App: "Akzente und technologische visuelle Details",
    color3Name: "⬛ Schwarz",
    color3Label: "Bedeutung:",
    color3Meaning: "Angeborene Eleganz, Solidität und Raffinesse",
    color3AppLabel: "Anwendung:",
    color3App: "Typografie und strukturelle Elemente",
    color4Name: "🟧 Gold/Orange",
    color4Label: "Bedeutung:",
    color4Meaning: "Kreativität, Energie, Innovation und Dynamik",
    color4AppLabel: "Anwendung:",
    color4App: "Betonungselemente und Handlungsaufforderungen",
    serviciosTitle: "💻 Angebotene Dienstleistungen",
    serviciosText: "Bei Sherval bieten wir eine breite Palette von Softwareentwicklungsdienstleistungen, die auf die spezifischen Bedürfnisse jedes Kunden zugeschnitten sind:",
    service1Title: "🖥️ Maßgeschneiderte Softwareentwicklung",
    service1Desc: "Wir erstellen maßgeschneiderte Lösungen, die perfekt zu den einzigartigen Anforderungen Ihres Unternehmens passen.",
    service2Title: "📱 Mobile Anwendungen",
    service2Desc: "Wir entwerfen und entwickeln native und plattformübergreifende Apps für iOS und Android mit intuitiven Benutzeroberflächen.",
    service3Title: "🌐 Webentwicklung",
    service3Desc: "Wir erstellen responsive und optimierte Websites, von Landingpages bis zu komplexen Plattformen.",
    service4Title: "📚 Beratung und Schulung",
    service4Desc: "Wir bieten Beratung für Personen und Unternehmen, die sich im Technologiebereich professionalisieren möchten.",
    service5Title: "🔗 Systemintegration",
    service5Desc: "Wir verbinden verschiedene Anwendungen und Systeme, um die operative Effizienz Ihres Unternehmens zu verbessern.",
    service6Title: "🧪 Softwaretests (QA)",
    service6Desc: "Wir führen umfassende Qualitätstests durch, um sicherzustellen, dass Ihre Software perfekt funktioniert.",
    service7Title: "🔧 Wartung und Support",
    service7Desc: "Wir bieten kontinuierliche Wartungs-, Update- und spezialisierte technische Supportdienste.",
    service8Title: "☁️ Cloud-Lösungen",
    service8Desc: "Wir implementieren und verwalten Cloud-Lösungen für größere Skalierbarkeit und Sicherheit.",
    propuestaTitle: "💡 Vorschlag",
    propuestaText: "Wir sind ein Unternehmen, das sich der Schaffung innovativer technologischer Lösungen widmet, die das Wachstum und die Effizienz unserer Kunden fördern.",
    canalesTitle: "💰 Zahlungsmethoden",
    canalesText: "Wir akzeptieren Nequi, Daviplata und PayPal.",
    contactoTitle: "📞 Kontaktieren Sie uns",
    contactEmail1: "📧 E-Mail:",
    contactPhone1: "📱 Telefon:",
    contactRole1: "💼 Position:",
    contactRoleText1: "Mitbegründer & Entwickler",
    contactEmail2: "📧 E-Mail:",
    contactPhone2: "📱 Telefon:",
    contactRole2: "💼 Position:",
    contactRoleText2: "Mitbegründerin & Entwicklerin",
    contactAddress: "📍 Adresse:",
    contactFormation: "🏢 Ausbildung:",
    contactFormationText: "SENA - Softwareprogrammierungstechniker",
    contactSchedule: "⏰ Bürozeiten:",
    contactScheduleText: "Montag bis Freitag 8:00 - 18:00 Uhr",
    audioTitle: "🔊 Audio-Erklärung",
    audioText: "Hören Sie sich die Projekterklärung an:",
    footer1: "© Laura Valentina Hernández Gómez",
    footer2: "© Sherman Andrés León Trigos",
    footer3: "<strong>Professionelle Softwareentwickler</strong>"
  },

  it: {
    titleName: "Sherval",
    titleSub: "Innovazione nello Sviluppo di Software",
    navVision: "Visione",
    navMision: "Missione",
    navValores: "Valori",
    navHistoria: "Storia",
    navColores: "Colori",
    navServicios: "Servizi",
    navPropuesta: "Proposta",
    navCanales: "Metodi di pagamento",
    navContacto: "Contattaci",
    navAudio: "Audio",
    visionTitle: "✨ Visione",
    visionText: "Diventare <strong>leader nello sviluppo di software innovativo</strong> in Colombia e nella regione, riconosciuti per la nostra capacità di anticipare le esigenze del mercato e offrire soluzioni tecnologiche che trasformano le industrie.",
    visionText2: "Aspiriamo a diventare il partner tecnologico preferito dalle aziende che cercano innovazione, qualità e impegno, espandendo la nostra portata a livello internazionale e contribuendo allo sviluppo tecnologico della regione.",
    misionTitle: "🚀 Missione",
    misionText: "Sviluppare <strong>soluzioni software innovative e di alta qualità</strong> che favoriscano la crescita e l'efficienza dei nostri clienti attraverso l'eccellenza tecnica, la stretta collaborazione e un impegno incrollabile per la soddisfazione degli utenti.",
    misionText2: "Ci sforziamo di comprendere le esigenze uniche di ogni cliente e trasformarle in prodotti tecnologici robusti, scalabili e facili da usare che generino valore reale per le loro imprese.",
    valoresTitle: "💎 Valori Aziendali",
    valoresIntro: "I nostri valori sono i pilastri che guidano ogni decisione, progetto e relazione con i nostri clienti:",
    valor1Title: "1. Rispetto",
    valor1Desc: "Teniamo conto di ciò che il cliente desidera e lo guidiamo nel miglior modo possibile. Valorizziamo le idee e le esigenze di ogni persona.",
    valor2Title: "2. Responsabilità",
    valor2Desc: "Consegniamo ciò che è promesso in tempo e ci impegniamo profondamente per il successo di ogni progetto. I nostri clienti possono fidarsi di noi.",
    valor3Title: "3. Onestà",
    valor3Desc: "Il lavoro seguirà un processo trasparente senza tabù con il cliente. Comunichiamo apertamente su progressi, sfide e soluzioni.",
    valor4Title: "4. Efficienza",
    valor4Desc: "Le risorse del sistema saranno facili da usare e modificare e saranno garantite. Ottimizziamo processi e risorse per fornire il massimo valore.",
    valor5Title: "5. Durabilità",
    valor5Desc: "I programmi e il lavoro saranno piuttosto resistenti nel tempo. Sviluppiamo software pensando al lungo termine.",
    valor6Title: "6. Sicurezza",
    valor6Desc: "Questo sarà offerto permanentemente durante tutto il processo con gli utenti. La protezione dei dati è una priorità in ogni riga di codice.",
    valor7Title: "7. Perseveranza",
    valor7Desc: "Manterremo la coerenza per scalare gli obiettivi dell'azienda. Non ci arrendiamo di fronte alle sfide e cerchiamo continuamente di migliorare.",
    historiaTitle: "📖 Storia",
    historiaText: "<strong>Sherval</strong> è un'azienda creata da due giovani appassionati di programmazione: <strong>Sherman Andrés León Trigos</strong> e <strong>Laura Valentina Hernández Gómez</strong>, formati in <strong>Programmazione Software presso il SENA</strong>.",
    historiaText2: "La nostra azienda è nata da un progetto accademico finale che si è trasformato in un'azienda consolidata con una visione per il futuro. Condividiamo una missione comune: creare soluzioni tecnologiche innovative che facciano la differenza nella vita delle persone e nella crescita delle imprese.",
    coloresTitle: "🎨 Colori Aziendali",
    coloresText: "I colori utilizzati nel nostro marchio trasmettono significati importanti che riflettono la nostra identità e i nostri valori:",
    color1Name: "🔷 Blu Scuro",
    color1Label: "Significato:",
    color1Meaning: "Serenità, fiducia, intelligenza e professionalità",
    color1AppLabel: "Applicazione:",
    color1App: "Colore principale nel logo e materiali aziendali",
    color2Name: "⚪ Argento",
    color2Label: "Significato:",
    color2Meaning: "Purezza, innovazione, modernità e umiltà",
    color2AppLabel: "Applicazione:",
    color2App: "Accenti e dettagli visivi tecnologici",
    color3Name: "⬛ Nero",
    color3Label: "Significato:",
    color3Meaning: "Eleganza innata, solidità e raffinatezza",
    color3AppLabel: "Applicazione:",
    color3App: "Tipografia ed elementi strutturali",
    color4Name: "🟧 Oro/Arancione",
    color4Label: "Significato:",
    color4Meaning: "Creatività, energia, innovazione e dinamismo",
    color4AppLabel: "Applicazione:",
    color4App: "Elementi di enfasi e inviti all'azione",
    serviciosTitle: "💻 Servizi Offerti",
    serviciosText: "In Sherval offriamo un'ampia gamma di servizi di sviluppo software progettati per soddisfare le esigenze specifiche di ogni cliente:",
    service1Title: "🖥️ Sviluppo Software su Misura",
    service1Desc: "Creiamo soluzioni personalizzate che si adattano perfettamente ai requisiti unici della vostra azienda.",
    service2Title: "📱 Applicazioni Mobile",
    service2Desc: "Progettiamo e sviluppiamo app native e multipiattaforma per iOS e Android con interfacce intuitive.",
    service3Title: "🌐 Sviluppo Web",
    service3Desc: "Creiamo siti web reattivi e ottimizzati, dalle landing page alle piattaforme complesse.",
    service4Title: "📚 Consulenza e Formazione",
    service4Desc: "Forniamo consulenza a persone e aziende che vogliono professionalizzarsi nell'area tecnologica.",
    service5Title: "🔗 Integrazione di Sistemi",
    service5Desc: "Colleghiamo diverse applicazioni e sistemi per migliorare l'efficienza operativa della vostra azienda.",
    service6Title: "🧪 Test Software (QA)",
    service6Desc: "Eseguiamo test di qualità esaustivi per garantire che il vostro software funzioni perfettamente.",
    service7Title: "🔧 Manutenzione e Supporto",
    service7Desc: "Offriamo servizi continui di manutenzione, aggiornamenti e supporto tecnico specializzato.",
    service8Title: "☁️ Soluzioni Cloud",
    service8Desc: "Implementiamo e gestiamo soluzioni cloud per maggiore scalabilità e sicurezza.",
    propuestaTitle: "💡 Proposta",
    propuestaText: "Siamo un'azienda dedicata alla creazione di soluzioni tecnologiche innovative che favoriscono la crescita e l'efficienza dei nostri clienti.",
    canalesTitle: "💰 Metodi di Pagamento",
    canalesText: "Accettiamo Nequi, Daviplata e PayPal.",
    contactoTitle: "📞 Contattaci",
    contactEmail1: "📧 Email:",
    contactPhone1: "📱 Telefono:",
    contactRole1: "💼 Posizione:",
    contactRoleText1: "Co-fondatore & Sviluppatore",
    contactEmail2: "📧 Email:",
    contactPhone2: "📱 Telefono:",
    contactRole2: "💼 Posizione:",
    contactRoleText2: "Co-fondatrice & Sviluppatrice",
    contactAddress: "📍 Indirizzo:",
    contactFormation: "🏢 Formazione:",
    contactFormationText: "SENA - Tecnici di Programmazione Software",
    contactSchedule: "⏰ Orario d'ufficio:",
    contactScheduleText: "Lunedì a Venerdì 8:00 - 18:00",
    audioTitle: "🔊 Spiegazione Audio",
    audioText: "Ascolta la spiegazione del progetto:",
    footer1: "© Laura Valentina Hernández Gómez",
    footer2: "© Sherman Andrés León Trigos",
    footer3: "<strong>Sviluppatori di Software Professionisti</strong>"
  },

  pt: {
    titleName: "Sherval",
    titleSub: "Inovação no Desenvolvimento de Software",
    navVision: "Visão",
    navMision: "Missão",
    navValores: "Valores",
    navHistoria: "História",
    navColores: "Cores",
    navServicios: "Serviços",
    navPropuesta: "Proposta",
    navCanales: "Métodos de pagamento",
    navContacto: "Contate-nos",
    navAudio: "Áudio",
    visionTitle: "✨ Visão",
    visionText: "Tornar-se <strong>líderes no desenvolvimento de software inovador</strong> na Colômbia e na região, sendo reconhecidos por nossa capacidade de antecipar as necessidades do mercado e oferecer soluções tecnológicas que transformam indústrias.",
    visionText2: "Aspiramos a nos tornar o parceiro tecnológico preferido de empresas que buscam inovação, qualidade e compromisso, expandindo nosso alcance internacionalmente e contribuindo para o desenvolvimento tecnológico da região.",
    misionTitle: "🚀 Missão",
    misionText: "Desenvolver <strong>soluções de software inovadoras e de alta qualidade</strong> que impulsionem o crescimento e a eficiência de nossos clientes, através da excelência técnica, colaboração próxima e um compromisso inabalável com a satisfação dos usuários.",
    misionText2: "Nos esforçamos para compreender as necessidades únicas de cada cliente e transformá-las em produtos tecnológicos robustos, escaláveis e fáceis de usar que gerem valor real para seus negócios.",
    valoresTitle: "💎 Valores Corporativos",
    valoresIntro: "Nossos valores são os pilares que guiam cada decisão, projeto e relacionamento com nossos clientes:",
    valor1Title: "1. Respeito",
    valor1Desc: "Levamos em conta o que o cliente deseja e o orientamos da melhor maneira possível. Valorizamos as ideias e necessidades de cada pessoa.",
    valor2Title: "2. Responsabilidade",
    valor2Desc: "Entregamos o que é prometido no prazo e nos comprometemos profundamente com o sucesso de cada projeto. Nossos clientes podem confiar em nós.",
    valor3Title: "3. Honestidade",
    valor3Desc: "O trabalho seguirá um processo transparente sem tabus com o cliente. Comunicamos abertamente sobre progressos, desafios e soluções.",
    valor4Title: "4. Eficiência",
    valor4Desc: "Os recursos do sistema serão fáceis de usar e modificar, além de contar com garantia. Otimizamos processos e recursos para entregar o máximo valor.",
    valor5Title: "5. Durabilidade",
    valor5Desc: "Os programas e trabalhos serão bastante resistentes ao longo do tempo. Desenvolvemos software pensando no longo prazo.",
    valor6Title: "6. Segurança",
    valor6Desc: "Esta será oferecida permanentemente durante todo o processo com os usuários. A proteção de dados é uma prioridade em cada linha de código.",
    valor7Title: "7. Perseverança",
    valor7Desc: "Manteremos consistência para escalar os objetivos da empresa. Não desistimos diante dos desafios e buscamos continuamente melhorar.",
    historiaTitle: "📖 História",
    historiaText: "<strong>Sherval</strong> é uma empresa criada por dois jovens apaixonados por programação: <strong>Sherman Andrés León Trigos</strong> e <strong>Laura Valentina Hernández Gómez</strong>, formados em <strong>Programação de Software no SENA</strong>.",
    historiaText2: "Nossa empresa nasceu de um projeto acadêmico final que se transformou em uma empresa consolidada com visão de futuro. Compartilhamos uma missão comum: criar soluções tecnológicas inovadoras que façam a diferença na vida das pessoas e no crescimento das empresas.",
    coloresTitle: "🎨 Cores Corporativas",
    coloresText: "As cores utilizadas em nossa marca transmitem significados importantes que refletem nossa identidade e valores:",
    color1Name: "🔷 Azul Escuro",
    color1Label: "Significado:",
    color1Meaning: "Serenidade, confiança, inteligência e profissionalismo",
    color1AppLabel: "Aplicação:",
    color1App: "Cor principal no logo e materiais corporativos",
    color2Name: "⚪ Prateado",
    color2Label: "Significado:",
    color2Meaning: "Pureza, inovação, modernidade e humildade",
    color2AppLabel: "Aplicação:",
    color2App: "Acentos e detalhes visuais tecnológicos",
    color3Name: "⬛ Preto",
    color3Label: "Significado:",
    color3Meaning: "Elegância inata, solidez e sofisticação",
    color3AppLabel: "Aplicação:",
    color3App: "Tipografia e elementos estruturais",
    color4Name: "🟧 Dourado/Laranja",
    color4Label: "Significado:",
    color4Meaning: "Criatividade, energia, inovação e dinamismo",
    color4AppLabel: "Aplicação:",
    color4App: "Elementos de ênfase e chamadas para ação",
    serviciosTitle: "💻 Serviços Oferecidos",
    serviciosText: "Na Sherval oferecemos uma ampla gama de serviços de desenvolvimento de software projetados para atender às necessidades específicas de cada cliente:",
    service1Title: "🖥️ Desenvolvimento de Software sob Medida",
    service1Desc: "Criamos soluções personalizadas que se adaptam perfeitamente aos requisitos únicos do seu negócio.",
    service2Title: "📱 Aplicativos Móveis",
    service2Desc: "Projetamos e desenvolvemos apps nativos e multiplataforma para iOS e Android com interfaces intuitivas.",
    service3Title: "🌐 Desenvolvimento Web",
    service3Desc: "Criamos sites responsivos e otimizados, desde landing pages até plataformas complexas.",
    service4Title: "📚 Consultoria e Treinamento",
    service4Desc: "Fornecemos consultoria para pessoas e empresas que desejam se profissionalizar na área tecnológica.",
    service5Title: "🔗 Integração de Sistemas",
    service5Desc: "Conectamos diferentes aplicativos e sistemas para melhorar a eficiência operacional da sua empresa.",
    service6Title: "🧪 Testes de Software (QA)",
    service6Desc: "Realizamos testes de qualidade exaustivos para garantir que seu software funcione perfeitamente.",
    service7Title: "🔧 Manutenção e Suporte",
    service7Desc: "Oferecemos serviços contínuos de manutenção, atualizações e suporte técnico especializado.",
    service8Title: "☁️ Soluções em Nuvem",
    service8Desc: "Implementamos e gerenciamos soluções em nuvem para maior escalabilidade e segurança.",
    propuestaTitle: "💡 Proposta",
    propuestaText: "Somos uma empresa dedicada a criar soluções tecnológicas inovadoras que impulsionam o crescimento e a eficiência de nossos clientes.",
    canalesTitle: "💰 Métodos de Pagamento",
    canalesText: "Aceitamos Nequi, Daviplata e PayPal.",
    contactoTitle: "📞 Contate-nos",
    contactEmail1: "📧 E-mail:",
    contactPhone1: "📱 Telefone:",
    contactRole1: "💼 Cargo:",
    contactRoleText1: "Co-fundador & Desenvolvedor",
    contactEmail2: "📧 E-mail:",
    contactPhone2: "📱 Telefone:",
    contactRole2: "💼 Cargo:",
    contactRoleText2: "Co-fundadora & Desenvolvedora",
    contactAddress: "📍 Endereço:",
    contactFormation: "🏢 Formação:",
    contactFormationText: "SENA - Técnicos em Programação de Software",
    contactSchedule: "⏰ Horário de atendimento:",
    contactScheduleText: "Segunda a Sexta 8:00 - 18:00",
    audioTitle: "🔊 Explicação em Áudio",
    audioText: "Ouça a explicação do projeto:",
    footer1: "© Laura Valentina Hernández Gómez",
    footer2: "© Sherman Andrés León Trigos",
    footer3: "<strong>Desenvolvedores de Software Profissionais</strong>"
  },

  ja: {
    titleName: "Sherval",
    titleSub: "ソフトウェア開発におけるイノベーション",
    navVision: "ビジョン",
    navMision: "ミッション",
    navValores: "価値観",
    navHistoria: "歴史",
    navColores: "カラー",
    navServicios: "サービス",
    navPropuesta: "提案",
    navCanales: "支払い方法",
    navContacto: "お問い合わせ",
    navAudio: "オーディオ",
    visionTitle: "✨ ビジョン",
    visionText: "コロンビアと地域における<strong>革新的なソフトウェア開発のリーダー</strong>となり、市場のニーズを予測し、業界を変革する技術ソリューションを提供する能力で認められることを目指します。",
    visionText2: "革新、品質、コミットメントを求める企業の好ましい技術パートナーとなり、国際的に範囲を拡大し、地域の技術開発に貢献することを目指しています。",
    misionTitle: "🚀 ミッション",
    misionText: "技術的卓越性、緊密な協力、ユーザー満足への揺るぎないコミットメントを通じて、クライアントの成長と効率を促進する<strong>革新的で高品質のソフトウェアソリューション</strong>を開発します。",
    misionText2: "各クライアントの独自のニーズを理解し、ビジネスに真の価値を生み出す堅牢でスケーラブルで使いやすい技術製品に変換することに努めています。",
    valoresTitle: "💎 企業価値",
    valoresIntro: "私たちの価値観は、すべての決定、プロジェクト、クライアントとの関係を導く柱です：",
    valor1Title: "1. 尊重",
    valor1Desc: "クライアントが望むことを考慮し、可能な限り最善の方法で導きます。各人のアイデアとニーズを大切にします。",
    valor2Title: "2. 責任",
    valor2Desc: "約束したものを時間通りに提供し、各プロジェクトの成功に深くコミットします。クライアントは私たちを信頼できます。",
    valor3Title: "3. 正直さ",
    valor3Desc: "作業はクライアントとのタブーのない透明なプロセスに従います。進捗、課題、解決策についてオープンにコミュニケーションします。",
    valor4Title: "4. 効率性",
    valor4Desc: "システムリソースは使いやすく、変更しやすく、保証付きです。プロセスとリソースを最適化して最大の価値を提供します。",
    valor5Title: "5. 耐久性",
    valor5Desc: "プログラムと作業は時間の経過とともにかなり耐性があります。長期的な視点でソフトウェアを開発します。",
    valor6Title: "6. セキュリティ",
    valor6Desc: "これはユーザーとのプロセス全体を通じて永続的に提供されます。データ保護はコードのすべての行で優先されます。",
    valor7Title: "7. 忍耐力",
    valor7Desc: "会社の目標を拡大するために一貫性を維持します。課題に直面してもあきらめず、継続的に改善を求めます。",
    historiaTitle: "📖 歴史",
    historiaText: "<strong>Sherval</strong>は、<strong>SENAのソフトウェアプログラミング</strong>で訓練を受けた、プログラミングに情熱を持つ2人の若者、<strong>Sherman Andrés León Trigos</strong>と<strong>Laura Valentina Hernández Gómez</strong>によって作られた会社です。",
    historiaText2: "私たちの会社は、将来のビジョンを持つ統合された会社に変革された最終的な学術プロジェクトから生まれました。私たちは共通の使命を共有しています：人々の生活とビジネスの成長に違いをもたらす革新的な技術ソリューションを作成することです。",
    coloresTitle: "🎨 コーポレートカラー",
    coloresText: "ブランドで使用される色は、私たちのアイデンティティと価値観を反映する重要な意味を伝えます：",
    color1Name: "🔷 ダークブルー",
    color1Label: "意味：",
    color1Meaning: "平静、信頼、知性、プロフェッショナリズム",
    color1AppLabel: "適用：",
    color1App: "ロゴと企業資料の主色",
    color2Name: "⚪ シルバー",
    color2Label: "意味：",
    color2Meaning: "純粋、革新、現代性、謙虚さ",
    color2AppLabel: "適用：",
    color2App: "アクセントと技術的な視覚的詳細",
    color3Name: "⬛ ブラック",
    color3Label: "意味：",
    color3Meaning: "生来のエレガンス、堅牢性、洗練",
    color3AppLabel: "適用：",
    color3App: "タイポグラフィと構造要素",
    color4Name: "🟧 ゴールド/オレンジ",
    color4Label: "意味：",
    color4Meaning: "創造性、エネルギー、革新、ダイナミズム",
    color4AppLabel: "適用：",
    color4App: "強調要素とコールトゥアクション",
    serviciosTitle: "💻 提供サービス",
    serviciosText: "Shervalでは、各クライアントの特定のニーズを満たすように設計された幅広いソフトウェア開発サービスを提供しています：",
    service1Title: "🖥️ カスタムソフトウェア開発",
    service1Desc: "ビジネスの独自の要件に完全に適合するカスタマイズされたソリューションを作成します。",
    service2Title: "📱 モバイルアプリケーション",
    service2Desc: "直感的なインターフェースを持つiOSとAndroid用のネイティブおよびクロスプラットフォームアプリを設計および開発します。",
    service3Title: "🌐 ウェブ開発",
    service3Desc: "ランディングページから複雑なプラットフォームまで、レスポンシブで最適化されたウェブサイトを作成します。",
    service4Title: "📚 コンサルティングとトレーニング",
    service4Desc: "技術分野でプロフェッショナルになりたい個人や企業にコンサルティングを提供します。",
    service5Title: "🔗 システム統合",
    service5Desc: "さまざまなアプリケーションとシステムを接続して、会社の運用効率を向上させます。",
    service6Title: "🧪 ソフトウェアテスト（QA）",
    service6Desc: "ソフトウェアが完璧に機能することを保証するために、徹底的な品質テストを実施します。",
    service7Title: "🔧 メンテナンスとサポート",
    service7Desc: "継続的なメンテナンス、更新、専門的な技術サポートサービスを提供します。",
    service8Title: "☁️ クラウドソリューション",
    service8Desc: "より大きなスケーラビリティとセキュリティのためにクラウドソリューションを実装および管理します。",
    propuestaTitle: "💡 提案",
    propuestaText: "私たちは、クライアントの成長と効率を促進する革新的な技術ソリューションを作成することに専念している会社です。",
    canalesTitle: "💰 支払い方法",
    canalesText: "Nequi、Daviplata、PayPalを受け付けています。",
    contactoTitle: "📞 お問い合わせ",
    contactEmail1: "📧 メール：",
    contactPhone1: "📱 電話：",
    contactRole1: "💼 役職：",
    contactRoleText1: "共同創設者兼開発者",
    contactEmail2: "📧 メール：",
    contactPhone2: "📱 電話：",
    contactRole2: "💼 役職：",
    contactRoleText2: "共同創設者兼開発者",
    contactAddress: "📍 住所：",
    contactFormation: "🏢 教育：",
    contactFormationText: "SENA - ソフトウェアプログラミング技術者",
    contactSchedule: "⏰ 営業時間：",
    contactScheduleText: "月曜日から金曜日 8:00 - 18:00",
    audioTitle: "🔊 音声説明",
    audioText: "プロジェクトの説明を聞く：",
    footer1: "© Laura Valentina Hernández Gómez",
    footer2: "© Sherman Andrés León Trigos",
    footer3: "<strong>プロフェッショナルソフトウェア開発者</strong>"
  },

  zh: {
    titleName: "Sherval",
    titleSub: "软件开发创新",
    navVision: "愿景",
    navMision: "使命",
    navValores: "价值观",
    navHistoria: "历史",
    navColores: "颜色",
    navServicios: "服务",
    navPropuesta: "提案",
    navCanales: "支付方式",
    navContacto: "联系我们",
    navAudio: "音频",
    visionTitle: "✨ 愿景",
    visionText: "成为哥伦比亚和该地区<strong>创新软件开发的领导者</strong>，以我们预测市场需求和提供改变行业的技术解决方案的能力而闻名。",
    visionText2: "我们渴望成为寻求创新、质量和承诺的公司的首选技术合作伙伴，将我们的影响力扩展到国际，并为该地区的技术发展做出贡献。",
    misionTitle: "🚀 使命",
    misionText: "通过技术卓越、紧密合作和对用户满意度的坚定承诺，开发<strong>创新、高质量的软件解决方案</strong>，推动客户的增长和效率。",
    misionText2: "我们努力理解每个客户的独特需求，并将其转化为强大、可扩展且易于使用的技术产品，为他们的业务创造真正的价值。",
    valoresTitle: "💎 企业价值观",
    valoresIntro: "我们的价值观是指导我们每一个决策、项目和与客户关系的支柱：",
    valor1Title: "1. 尊重",
    valor1Desc: "我们考虑客户的需求，并以最好的方式指导他们。我们重视每个人的想法和需求。",
    valor2Title: "2. 责任",
    valor2Desc: "我们按时交付承诺的内容，并深深致力于每个项目的成功。我们的客户可以信任我们。",
    valor3Title: "3. 诚实",
    valor3Desc: "工作将遵循与客户的透明流程，没有禁忌。我们公开沟通进展、挑战和解决方案。",
    valor4Title: "4. 效率",
    valor4Desc: "系统资源将易于使用和修改，并附带保修。我们优化流程和资源以提供最大价值。",
    valor5Title: "5. 耐用性",
    valor5Desc: "程序和工作将随着时间的推移具有相当的抵抗力。我们开发软件时考虑长期。",
    valor6Title: "6. 安全",
    valor6Desc: "这将在与用户的整个过程中永久提供。数据保护是每行代码的优先事项。",
    valor7Title: "7. 毅力",
    valor7Desc: "我们将保持一致性以扩大公司的目标。我们不会在挑战面前放弃，并不断寻求改进。",
    historiaTitle: "📖 历史",
    historiaText: "<strong>Sherval</strong>是由两位热衷于编程的年轻人创建的公司：<strong>Sherman Andrés León Trigos</strong>和<strong>Laura Valentina Hernández Gómez</strong>，他们在<strong>SENA的软件编程</strong>接受培训。",
    historiaText2: "我们的公司诞生于一个最终学术项目，该项目转变为一个具有未来愿景的综合公司。我们分享一个共同的使命：创建创新的技术解决方案，在人们的生活和企业增长中产生影响。",
    coloresTitle: "🎨 企业颜色",
    coloresText: "我们品牌中使用的颜色传达了反映我们身份和价值观的重要含义：",
    color1Name: "🔷 深蓝色",
    color1Label: "含义：",
    color1Meaning: "宁静、信任、智慧和专业",
    color1AppLabel: "应用：",
    color1App: "标志和企业材料中的主要颜色",
    color2Name: "⚪ 银色",
    color2Label: "含义：",
    color2Meaning: "纯洁、创新、现代和谦逊",
    color2AppLabel: "应用：",
    color2App: "重音和技术视觉细节",
    color3Name: "⬛ 黑色",
    color3Label: "含义：",
    color3Meaning: "天生的优雅、稳固和精致",
    color3AppLabel: "应用：",
    color3App: "排版和结构元素",
    color4Name: "🟧 金色/橙色",
    color4Label: "含义：",
    color4Meaning: "创造力、能量、创新和活力",
    color4AppLabel: "应用：",
    color4App: "强调元素和行动号召",
    serviciosTitle: "💻 提供的服务",
    serviciosText: "在Sherval，我们提供广泛的软件开发服务，旨在满足每个客户的特定需求：",
    service1Title: "🖥️ 定制软件开发",
    service1Desc: "我们创建完全适合您业务独特要求的定制解决方案。",
    service2Title: "📱 移动应用程序",
    service2Desc: "我们为iOS和Android设计和开发具有直观界面的原生和跨平台应用程序。",
    service3Title: "🌐 网站开发",
    service3Desc: "我们创建响应式和优化的网站，从着陆页到复杂平台。",
    service4Title: "📚 咨询和培训",
    service4Desc: "我们为希望在技术领域专业化的个人和公司提供咨询。",
    service5Title: "🔗 系统集成",
    service5Desc: "我们连接不同的应用程序和系统以提高您公司的运营效率。",
    service6Title: "🧪 软件测试（QA）",
    service6Desc: "我们进行详尽的质量测试，以确保您的软件完美运行。",
    service7Title: "🔧 维护和支持",
    service7Desc: "我们提供持续的维护、更新和专业的技术支持服务。",
    service8Title: "☁️ 云解决方案",
    service8Desc: "我们实施和管理云解决方案以实现更大的可扩展性和安全性。",
    propuestaTitle: "💡 提案",
    propuestaText: "我们是一家致力于创建创新技术解决方案的公司，推动客户的增长和效率。",
    canalesTitle: "💰 支付方式",
    canalesText: "我们接受Nequi、Daviplata和PayPal。",
    contactoTitle: "📞 联系我们",
    contactEmail1: "📧 电子邮件：",
    contactPhone1: "📱 电话：",
    contactRole1: "💼 职位：",
    contactRoleText1: "联合创始人兼开发人员",
    contactEmail2: "📧 电子邮件：",
    contactPhone2: "📱 电话：",
    contactRole2: "💼 职位：",
    contactRoleText2: "联合创始人兼开发人员",
    contactAddress: "📍 地址：",
    contactFormation: "🏢 教育：",
    contactFormationText: "SENA - 软件编程技术员",
    contactSchedule: "⏰ 办公时间：",
    contactScheduleText: "周一至周五 8:00 - 18:00",
    audioTitle: "🔊 音频说明",
    audioText: "收听项目说明：",
    footer1: "© Laura Valentina Hernández Gómez",
    footer2: "© Sherman Andrés León Trigos",
    footer3: "<strong>专业软件开发人员</strong>"
  }
};

// ==================== FUNCIÓN DE TRADUCCIÓN ====================
function applyLanguage(lang) {
  const t = translations[lang];
  if (!t) {
    console.warn(`Idioma "${lang}" no encontrado. Usando español por defecto.`);
    return;
  }
  
  // Actualizar todos los elementos traducibles
  for (const key in t) {
    const el = document.getElementById(key);
    if (el) {
      el.innerHTML = t[key];
    }
  }
  
  // Guardar preferencia de idioma en localStorage
  localStorage.setItem('selectedLanguage', lang);
  
  console.log(`Idioma cambiado a: ${lang}`);
}

// ==================== INICIALIZACIÓN ====================
document.addEventListener("DOMContentLoaded", () => {
  const selector = document.getElementById("languageSelector");
  if (!selector) {
    console.error("No se encontró el selector de idioma");
    return;
  }

  // Restaurar idioma guardado o usar español por defecto
  const savedLanguage = localStorage.getItem('selectedLanguage') || 'es';
  selector.value = savedLanguage;
  applyLanguage(savedLanguage);

  // Detectar cambio de idioma
  selector.addEventListener("change", () => {
    applyLanguage(selector.value);
  });
});
